use crate::error::AppError;
use crate::services::pdf_generator::{PdfGeneratorService, PdfReportData};
use base64::{engine::general_purpose, Engine as _};
use bytes::Bytes;
use docx_rs::*;
use headless_chrome::{Browser, LaunchOptions};
use sea_orm::DatabaseConnection;
use std::ffi::OsStr;
use tracing::{error, info, instrument, warn};
use uuid::Uuid;

pub struct WordGeneratorService;

impl WordGeneratorService {
    #[instrument(skip(db), fields(assessment_id = %assessment_id))]
    pub async fn generate_assessment_word(
        db: &DatabaseConnection,
        assessment_id: Uuid,
        organization_name: Option<String>,
        lang: Option<String>,
    ) -> Result<Bytes, AppError> {
        info!("Starting Word generation.");
        let lang = lang.unwrap_or_else(|| "en".to_string());
        let report_data = PdfGeneratorService::fetch_report_data(db, assessment_id, organization_name, &lang).await?;

        // 1. Capture Chart Image (if chart data exists)
        let chart_image = if report_data.chart_data.is_some() {
            let html = PdfGeneratorService::render_html_template(&report_data)?;
            Some(Self::capture_chart_image(&html).await?)
        } else {
            None
        };

        // 2. Generate DOCX
        let docx_bytes = Self::build_docx(&report_data, chart_image)?;
        Ok(Bytes::from(docx_bytes))
    }

    async fn capture_chart_image(html: &str) -> Result<Vec<u8>, AppError> {
        let browser = Browser::new(LaunchOptions {
            headless: true,
            sandbox: true,
            args: vec![OsStr::new("--no-sandbox"), OsStr::new("--disable-gpu")],
            ..Default::default()
        })
        .map_err(|e| AppError::InternalServerError(format!("Failed to launch browser: {}", e)))?;

        let tab = browser
            .new_tab()
            .map_err(|e| AppError::InternalServerError(format!("Failed to create tab: {}", e)))?;

        let data_url = format!(
            "data:text/html;base64,{}",
            general_purpose::STANDARD.encode(html)
        );
        tab.navigate_to(&data_url)
            .map_err(|e| AppError::InternalServerError(format!("Failed to navigate: {}", e)))?;

        // Wait for the chart image to be generated by the JS in report.html
        if let Err(e) = tab.wait_for_element("img#chartImage") {
            warn!(error = %e, "Chart image not found in HTML — skipping image.");
            return Err(AppError::InternalServerError("Chart image not found".to_string()));
        }

        // Extract the base64 src from the img#chartImage
        let img_src = tab
            .evaluate("document.getElementById('chartImage').src", false)
            .map_err(|e| AppError::InternalServerError(format!("Failed to get image src: {}", e)))?
            .value
            .ok_or_else(|| AppError::InternalServerError("Image src is empty".to_string()))?
            .as_str()
            .ok_or_else(|| AppError::InternalServerError("Image src is not a string".to_string()))?
            .to_string();

        let base64_data = img_src
            .strip_prefix("data:image/png;base64,")
            .ok_or_else(|| AppError::InternalServerError("Invalid image format".to_string()))?;

        let image_data = general_purpose::STANDARD
            .decode(base64_data)
            .map_err(|e| AppError::InternalServerError(format!("Failed to decode base64 image: {}", e)))?;

        Ok(image_data)
    }

    fn build_docx(data: &PdfReportData, chart_image: Option<Vec<u8>>) -> Result<Vec<u8>, AppError> {
        let mut doc = Docx::new();

        // 1. Header Section
        doc = doc.add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(&data.labels.title).size(40).bold().color("1e40af"))
                .align(AlignmentType::Center),
        );
        doc = doc.add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(&data.assessment_title).size(28).color("64748b"))
                .align(AlignmentType::Center),
        );
        doc = doc.add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(format!("{}: {}", data.labels.coop_prefix, data.organization_id)).size(24).color("94a3b8"))
                .align(AlignmentType::Center),
        );

        // Spacer
        doc = doc.add_paragraph(Paragraph::new());

        // 2. Table Section
        let mut table = Table::new(vec![]);
        
        // Table Headers
        table = table.add_row(TableRow::new(vec![
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&data.labels.category).bold().color("FFFFFF"))).shading(Shading::new().fill("1e40af")),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&data.labels.gap).bold().color("FFFFFF"))).shading(Shading::new().fill("1e40af")),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&data.labels.result).bold().color("FFFFFF"))).shading(Shading::new().fill("1e40af")),
            TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&data.labels.recommendations).bold().color("FFFFFF"))).shading(Shading::new().fill("1e40af")),
        ]));

        // Table Rows
        for row in &data.rows {
            let mut rec_para = Paragraph::new();
            if row.recommendations.is_empty() {
                rec_para = rec_para.add_run(Run::new().add_text(&data.labels.no_action_items).italic().color("94a3b8"));
            } else {
                for (i, rec) in row.recommendations.iter().enumerate() {
                    rec_para = rec_para.add_run(Run::new().add_text(format!("• {}", rec)));
                    if i < row.recommendations.len() - 1 {
                        rec_para = rec_para.add_run(Run::new().add_break(BreakType::TextWrapping));
                    }
                }
            }

            let gap_color = match row.gap_class.as_str() {
                "high" => "991b1b",
                "medium" => "854d0e",
                _ => "166534",
            };

            table = table.add_row(TableRow::new(vec![
                TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&row.category).bold())),
                TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&row.gap).bold().color(gap_color))),
                TableCell::new().add_paragraph(Paragraph::new().add_run(Run::new().add_text(&row.result))),
                TableCell::new().add_paragraph(rec_para),
            ]));
        }

        doc = doc.add_table(table);

        // 3. Chart Section
        if let Some(img_bytes) = chart_image {
            doc = doc.add_paragraph(Paragraph::new().page_break_before(true));
            doc = doc.add_paragraph(
                Paragraph::new()
                    .add_run(Run::new().add_text(&data.labels.chart_title).size(30).bold().color("1e40af"))
                    .align(AlignmentType::Left),
            );
            
            let pic = Pic::new(&img_bytes)
                .size(600 * 9525, 300 * 9525); // 1 px = 9525 EMU roughly, 600x300 px
            
            doc = doc.add_paragraph(Paragraph::new().add_run(Run::new().add_image(pic)));
        }

        // 4. Footer
        doc = doc.add_paragraph(Paragraph::new());
        doc = doc.add_paragraph(
            Paragraph::new()
                .add_run(Run::new().add_text(format!("{}: {}", data.labels.generated_at, data.generation_date)).size(20).color("64748b"))
                .align(AlignmentType::Center),
        );

        let mut buf = std::io::Cursor::new(Vec::new());
        doc.build()
            .pack(&mut buf)
            .map_err(|e| {
                error!(error = %e, "Failed to pack DOCX.");
                AppError::InternalServerError(format!("Word pack error: {}", e))
            })?;

        Ok(buf.into_inner())
    }
}

