export const currentStateDescriptions: Record<string, string[]> = {
  Technology: [
    "Legacy Systems",
    "Basic Digital Tools",
    "Partial Automation",
    "Cloud-Enabled",
    "Highly Scalable & Integrated",
  ],
  "Digital Culture": [
    "Digital Resistance",
    "Basic minimal Adoption",
    "Willing but Inconsistent",
    "Adoption with Leadership Support",
    "Fully Embedded Digital Culture",
  ],
  Skills: [
    "Insufficient Digital Skills",
    "Basic Digital Skills",
    "Moderate Skills, Limited to Certain Areas",
    "Widespread Digital Proficiency",
    "Advanced Expertise",
  ],
  Processes: [
    "Manual and inefficient processes.",
    "Efficient but manual",
    "Partially Automated",
    "Fully Automated inefficient",
    "Fully Automated efficient / integrated",
  ],
  Cybersecurity: [
    "No Cybersecurity Measures",
    "Basic Security",
    "Standard Security Protocols",
    "Proactive Cybersecurity",
    "Comprehensive Security Framework",
  ],
  "Customer Experience": [
    "No Digital Customer Interaction",
    "Basic Digital Presence",
    "Limited Digital Channels",
    "Multiple Digital Channels",
    "Seamless Omnichannel Experience",
  ],
  "Data & Analytics": [
    "No Data Collection or Use",
    "Basic Data Collection",
    "Data for Operational Reporting",
    "Advanced Data Analytics",
    "Data-Driven Organization",
  ],
  Innovation: [
    "No Innovation",
    "Occasional Innovation",
    "Innovation with Limited Scope",
    "Proactive Innovation Culture",
    "Innovation Leader",
  ],
};

export const desiredStateDescriptions: Record<string, string[]> = {
  Technology: [
    "Legacy Systems",
    "Basic Digital Tools",
    "Partial Automation",
    "Cloud-Enabled",
    "Highly Scalable & Integrated",
  ],
  "Digital Culture": [
    "Traditional Mindset (Analogue Culture)",
    "Digital Experimentation (Explorative Digital Culture)",
    "Digital Collaboration (Engaging Digital Culture)",
    "Adoption of Member-Centric Digitalization with Leadership Support (Integrative Digital Culture)",
    "Culture of Continuous Innovation and Digital Leadership (Transformative Digital Culture)",
  ],
  Skills: [
    "Insufficient Digital Literacy",
    "Basic Digital Literacy",
    "Functional Digital skills with limitations in certain areas",
    "Cross-functional and departmental Digital Competency",
    "Future-Ready Workforce with specialized expertise",
  ],
  Processes: [
    "Fully Manual Processes",
    "Digitized but Manual",
    "Partially Automated Processes",
    "Fully Automated Processes",
    "Integrated Automation through Digital Transformation",
  ],
  Cybersecurity: [
    "No Cybersecurity Measures",
    "Basic Security Measures",
    "Reactive Cybersecurity",
    "Proactive Cybersecurity",
    "Comprehensive Security Framework",
  ],
  "Customer Experience": [
    "No Digital Customer Interaction",
    "Basic Digital Presence",
    "Limited Digital Channels",
    "Multi-Channel Engagement",
    "Omnichannel Excellence",
  ],
  "Data & Analytics": [
    "No Data Collection or Use",
    "Basic Data Collection & Storage",
    "Operational Reporting Only",
    "Advanced Analytics & Insights",
    "Data-Driven Decision Making Culture",
  ],
  Innovation: [
    "No Focus on Innovation",
    "Occasional Innovation Efforts",
    "Focused Innovation Initiatives",
    "Proactive Innovation Culture",
    "Continuous Innovation & Disruption Leadership",
  ],
};
